services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: lemine
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  job_tracker_api:
    image: med3744lemin/job_search_app-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/job_tracker
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

