name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
  push:
    branches:
      - master

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 14.5
  POSTGRESQL_DB: job_tracker
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cash: 'maven'
      - name: Maven Clean Package
        run: mvn -ntp -B verify