name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**

  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: 'job_tracker'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'password'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          distribution: 'temurin'
          java-version: '17'
          cash: 'maven'
      - name: Maven Clean Package
        run: mvn -ntp -B verify